### ISSUE TITLE
structure: Expected DATAEND 

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1076]
Received this issue from a SAP original program. It probably is caused by the "OF COMMON PART".

![image](https://user-images.githubusercontent.com/53995991/88257864-0d2b9000-ccbf-11ea-9d7e-06b6bfd97400.png)

![image](https://user-images.githubusercontent.com/53995991/88258005-61367480-ccbf-11ea-9674-69666d22af99.png)

**Comment by larshp** [comment]
The playground errors shown in the playground screenshot is not the same as the original errors

**Comment by larshp** [comment]
parts of this has been fixed, but not really sure

**Comment by ed-holland** [comment]
Examples for which the issue still exists (from IDES)
MV45ACOM
VBAPDATA
IDOCDATA (no enhancement points)

**Comment by larshp** [comment]
try again, 2.38.9

**Comment by ed-holland** [comment]
Sorry, no change
![image](https://user-images.githubusercontent.com/53995991/88890512-06ae9280-d242-11ea-9d06-67952ddb518c.png)

**Comment by larshp** [comment]
are the following still in the list?
MV45ACOM
VBAPDATA
IDOCDATA

**Comment by ed-holland** [comment]
The last 2 are in the screenshot. Here the first.
![image](https://user-images.githubusercontent.com/53995991/88891498-9dc81a00-d243-11ea-8a5e-197f72d07768.png)

**Comment by larshp** [comment]
try again, 2.38.10

**Comment by ed-holland** [comment]
Sorry, no change.

**Comment by larshp** [comment]
try 2.38.11,

One bug at a time, https://www.youtube.com/watch?v=18cW_yHo3PY

**Comment by ed-holland** [comment]
Yeah... we are almost there.... 

Much Better. Thanks.
This is the only DATAEND error left.
/tmp/abaplint-PiAfkO/src/vz/theaddat.prog.abap[1, 1]                       - Expected DATAEND (structure)

name with a dash. Was there not another issue with that?
![image](https://user-images.githubusercontent.com/53995991/89034973-57091b80-d33a-11ea-9e17-4f6e6a82d803.png)

**Comment by larshp** [comment]
yes, dashes in DATA names is a problem, suggest closing this issue and opening a new one regarding dashes in DATA names

**Comment by ed-holland** [comment]
Thanks
