### ISSUE TITLE
Include /REDWOOD/L1IDOCTOP not found (check_include)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1129]
Issue:
`./src/idoc/#redwood#1idoc.fugr.#redwood#sapl1idoc.abap[4, 3]            - Include /REDWOOD/L1IDOCTOP not found (check_include)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89130340-663bc500-d504-11ea-89c3-e41e46ffbd70.png)

SCI & AbapLint (2.38.14) produce the same issue.

The source code of the main program and the include are both part of the repostory.

**Comment by larshp** [comment]
the unit test for this scenario is at https://github.com/abaplint/abaplint/blob/master/packages/core/test/rules/check_include.ts#L90

try comparing the filenames and contents to see if there is something missing

also try copying the files to local PC, and then delete as much as possible while keeping the error

**Comment by ed-holland** [comment]
I've removed all from the fugr main program beside the include. The include only containing the function-pool line.
The issue persists.
Also renaming the fugr without the 1 does not resolve it.
Any other sugguestions?

**Comment by larshp** [comment]
try again, I cannot reproduce this on command line, this could have been fixed by https://github.com/abaplint/abaplint/commit/d8f5db23b309fa57621ed9503b1f6a20dad06863

only a problem in vscode

**Comment by larshp** [comment]
try again, 2.39.26 published

**Comment by ed-holland** [comment]
Tried using the docker image and the issue persists.
![image](https://user-images.githubusercontent.com/53995991/91743189-b8c9d900-ebb7-11ea-8dc4-0582ce4438ac.png)

**Comment by ed-holland** [comment]
The cause has been found (thanks @larshp). The fuba RS_GET_ALL_INCLUDES was not finding any includes. Although there where no inactive objects, activation of the fugr main program resolved the problem.
